# Generated by Django 5.0.4 on 2024-04-22 07:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='LineString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('lines', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_app.points')),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('lines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_app.linestring')),
            ],
        ),
    ]
